/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<string, Date | string, Date | string>;

export interface Accounts {
  created_at: Generated<Timestamp>;
  /**
   * Plaintext account-level date/time display prefs ({ dateStyle, timeStyle, timeZoneEnc }). An explicit timezone is sealed enc:v1: in timeZoneEnc so the server stays blind.
   */
  date_preferences: Json | null;
  email: string;
  /**
   * E2EE enc:v1: blob holding the whole provider-keys map (key, keyPreview, addedAt per provider), sealed client-side under the account VMK. Server stores and returns it verbatim and cannot decrypt.
   */
  encrypted_api_keys: string | null;
  /**
   * Stamped once when any of the account's submissions is hard-rejected; surfaced to the operator, never auto-cleared.
   */
  flagged_for_review_at: Timestamp | null;
  id: string;
  /**
   * Parent UI language (BCP-47 short code, e.g. en/de). Durable source of truth; cached client-side in the NEXT_LOCALE cookie and re-seeded at login.
   */
  language: Generated<string>;
  max_custom_personas: Generated<number>;
  /**
   * Max kid profiles for this account (copied from the plan by applyPlanToAccount). NULL = unlimited; POST /api/kids treats NULL as no limit. A non-NULL number still caps this one account without needing a new plan.
   */
  max_kids: number | null;
  max_storage_mb_per_kid: Generated<number>;
  memory_tier: Generated<"basic" | "advanced" | "full">;
  model_config: Json | null;
  /**
   * Max publication submissions per UTC calendar month (every submit counts — each triggers a paid AI review). Plan-entitlement pattern: per-account override allowed.
   */
  monthly_game_publication_limit: Generated<number>;
  /**
   * Plaintext account-level notification toggles ({ friend_approval_email, ... }). Deliberately NOT E2EE: the server reads these to decide whether to send transactional email (e.g. friend-request approval). Default: all on.
   */
  notification_preferences: Generated<Json>;
  /**
   * Nostr public key of the vault root (x-only schnorr pubkey, lowercase hex; UI shows bech32 npub1…). Set once at vault bootstrap; unique — one npub binds to one account. Never store the nsec.
   */
  npub: string | null;
  /**
   * enc:v1: sealed 4-digit parent PIN gating the parent area; null = no PIN. Client-set/verified; server-blind.
   */
  parent_pin_enc: string | null;
  /**
   * Deliberately PUBLIC author byline for dodi Discover (like kids.social_id). Lowercase [a-z0-9_], 3-15 chars, unique. NULL until the first publish.
   */
  publication_handle: string | null;
  /**
   * Handle of the plan the account subscribed to (FK → platform_plans.handle). The plan's entitlement columns (max_kids, …, memory_tier) are COPIED onto the account by applyPlanToAccount so per-account caps can be overridden without a new plan; enforcement always reads the account columns.
   */
  subscribed_plan: Generated<string>;
  updated_at: Generated<Timestamp>;
  /**
   * Opaque wrapped Vault Master Key material (StoredVaultKeys). Server cannot decrypt it. See src/lib/vault.
   */
  vault_keys: Json | null;
}

export interface Activities {
  account_id: string;
  created_at: Generated<Timestamp>;
  event: string;
  /**
   * Soft reference so the activity feed can name a game client-side; the title itself is E2EE and must never be written into message.
   */
  game_id: string | null;
  id: Generated<string>;
  kid_id: string;
  message: string;
  occurred_at: Generated<Timestamp>;
  persona_id: string | null;
}

export interface AiUsageLogs {
  account_id: string;
  cache_read_tokens: number | null;
  cache_write_tokens: number | null;
  created_at: Generated<Timestamp>;
  event_type: "game_create" | "game_edit" | "game_plan" | "game_analysis" | "game_text_generation" | "game_translation" | "memory_update" | "voice_minutes";
  game_id: string | null;
  id: Generated<string>;
  input_tokens: number | null;
  kid_id: string | null;
  meta_learning_goal_chars: number | null;
  meta_memory_chars: number | null;
  meta_output_chars: number | null;
  meta_parent_notes_chars: number | null;
  meta_persona_chars: number | null;
  meta_prompt_chars: number | null;
  meta_success_def_chars: number | null;
  meta_tags_chars: number | null;
  meta_turns: number | null;
  meta_validation_retries: number | null;
  model: string;
  output_tokens: number | null;
  provider: string;
  voice_seconds: number | null;
}

export interface AuthAccounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Timestamp;
  user_id: string;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  token: string;
  updated_at: Timestamp;
  user_agent: string | null;
  user_id: string;
}

export interface AuthUsers {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: boolean;
  id: Generated<string>;
  image: string | null;
  invite_code: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface AuthVerifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface Devices {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  device_id: string;
  enrolled_at: Timestamp | null;
  id: Generated<string>;
  kem_public_key: string;
  last_seen_at: Timestamp | null;
  name: string | null;
  pairing_code: string | null;
  sign_public_key: string;
  status: Generated<"pending" | "active" | "revoked">;
  updated_at: Generated<Timestamp>;
}

export interface ErrorLogs {
  account_id: string | null;
  context: string;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  error_name: string | null;
  game_id: string | null;
  http_status: number | null;
  id: Generated<string>;
  kid_id: string | null;
  meta: Json | null;
  model: string | null;
  provider: string | null;
  type: "client" | "server";
  user_agent: string | null;
}

export interface Friendships {
  addressee_accepted: Generated<boolean>;
  addressee_account_id: string;
  addressee_card: string | null;
  addressee_kid_id: string;
  addressee_parent_ok: boolean | null;
  blocked_by: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  nickname: string | null;
  requester_account_id: string;
  requester_card: string | null;
  requester_kid_id: string;
  requester_parent_ok: boolean | null;
  requester_preview_card: string | null;
  status: Generated<"pending" | "awaiting_parent" | "accepted" | "rejected" | "blocked">;
  updated_at: Generated<Timestamp>;
}

export interface GameFavorites {
  account_id: string;
  created_at: Generated<Timestamp>;
  game_id: string;
  id: Generated<string>;
  kid_id: string;
}

export interface GamePlays {
  account_id: string;
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  final_progress: Generated<Numeric>;
  game_id: string;
  id: Generated<string>;
  kid_id: string;
  metrics: Generated<Json>;
  progress_kind: Generated<"goal" | "open">;
  started_at: Generated<Timestamp>;
  succeeded: Generated<boolean>;
  succeeded_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface GamePublicationRequests {
  account_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  id: Generated<string>;
  /**
   * Draft-only: per-locale listing title/description, sealed client-side (enc:v1:); cleared at submit.
   */
  listing_translations_enc: string | null;
  /**
   * NULL while the request is undecided (pending review or withdrawn before a verdict); approved or rejected once stamped.
   */
  outcome: "approved" | "rejected" | null;
  publication_game_id: string | null;
  rejection_kind: "hard" | "soft" | null;
  rejection_reasons: Json | null;
  /**
   * The parent's private E2EE game the submission was forked from. A hard-rejected source_game_id can never be resubmitted.
   */
  source_game_id: string | null;
  /**
   * When the parent submitted for review; NULL = draft (translations prepared, not yet submitted).
   */
  submitted_at: Timestamp | null;
}

export interface Games {
  account_id: string | null;
  agent_transcript_enc: string | null;
  /**
   * Who approved the publication: system (automated review agent) or admin (manual).
   */
  approved_by: "system" | "admin" | null;
  /**
   * Locales the published bundle + listing translations fully cover (derived at publish/backfill; NULL on private rows).
   */
  available_locales: string[] | null;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext for system games and publication copies. Server cannot decrypt.
   */
  code_bundle: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<"system" | "parent" | "kid">;
  current_game_version_id: string | null;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext for system games and publication copies. Server cannot decrypt.
   */
  description: Generated<string>;
  estimated_duration_minutes: Generated<number>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_system: Generated<boolean>;
  kid_id: string | null;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext for system games and publication copies. Server cannot decrypt.
   */
  learning_goal: Generated<string>;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext for system games and publication copies. Server cannot decrypt.
   */
  markdown: Generated<string>;
  metadata: Generated<Json>;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext path/data URL for system games and publication copies. Server cannot decrypt.
   */
  preview_image: string | null;
  progress_kind: Generated<"goal" | "open">;
  /**
   * Set on a publication COPY when the parent submits it for review. Non-NULL also means: this row is plaintext.
   */
  publication_requested_at: Timestamp | null;
  /**
   * Stamped by the review pass once the submission is approved.
   */
  published_at: Timestamp | null;
  /**
   * Authorship, as opposed to account_id which is ownership (CASCADE). Kept separate so an approved listing can later be re-parented to a dodi-owned catalog row without losing credit.
   */
  published_by_account_id: string | null;
  /**
   * Stamped by the review pass when a submission is rejected. Only ever set on publication copies; cleared on resubmit.
   */
  rejected_at: Timestamp | null;
  /**
   * PROJECT.md "rejection type": hard (permanent, source can never be resubmitted, account flagged) or soft (demand changes, resubmit allowed).
   */
  rejection_kind: "hard" | "soft" | null;
  /**
   * Array of {code, note}: code from @dodi/protocol/publication-review REJECTION_CODES, note = the agent's plain-text explanation for the parent.
   */
  rejection_reasons: Json | null;
  /**
   * Security-agent attempts consumed. Doubles as the optimistic claim token for concurrent workers (UPDATE ... WHERE review_attempts = seen). Parked for the operator once it reaches the max.
   */
  review_attempts: Generated<number>;
  source_game_id: string | null;
  /**
   * jsonb holding an enc:v1: STRING scalar for private games (sealed SuccessCriteria JSON); a plain object for system games and publication copies. Server cannot decrypt.
   */
  success_criteria: Generated<Json>;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext for system games and publication copies. Server cannot decrypt.
   */
  success_definition: Generated<string>;
  system_key: string | null;
  tags: Generated<string[]>;
  target_age_max: Generated<number>;
  target_age_min: Generated<number>;
  /**
   * E2EE enc:v1: under the account VMK for private games; plaintext for system games and publication copies. Server cannot decrypt.
   */
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface GameSharings {
  account_id: string;
  created_at: Generated<Timestamp>;
  game_id: string;
  id: Generated<string>;
  kid_id: string | null;
}

export interface GameSnapshots {
  account_id: string;
  created_at: Generated<Timestamp>;
  friendship_id: string | null;
  /**
   * Soft reference to the source game (the sender's game for received snapshots); NULL only after game deletion.
   */
  game_id: string | null;
  id: Generated<string>;
  /**
   * Opaque light gallery blob (title, game title, thumbnail). origin=own: enc:v1: JSON under the account VMK; origin=received: SealedEnvelope JSON to the kid's friend KEM key, signed by the sender kid. Server cannot decrypt.
   */
  info_enc: string;
  kid_id: string;
  /**
   * own = manually saved by this kid; received = delivered by a friend; autosave = the kid's single resume slot per game (hidden from the collection, overwritten in place).
   */
  origin: Generated<"own" | "received" | "autosave">;
  /**
   * Approximate plaintext payload size in bytes — recorded for future per-kid storage quota enforcement.
   */
  payload_bytes: Generated<number>;
  /**
   * Opaque heavy blob (game code + metadata + restorable save state), sealed like info_enc. Self-contained: outlives game edits/deletion. Server cannot decrypt.
   */
  payload_enc: string;
  sender_kid_id: string | null;
  /**
   * Sender-side "sent" marker on own rows: the friend kid this snapshot was delivered to when it was created by sharing (share implies save). NULL for plain saves; set NULL if the friend kid is deleted.
   */
  shared_with_kid_id: string | null;
  updated_at: Generated<Timestamp>;
  viewed_at: Timestamp | null;
}

export interface GameTranslations {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  game_id: string;
  id: Generated<string>;
  locale: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface GameVersions {
  account_id: string;
  /**
   * E2EE enc:v1: — copied verbatim from games.code_bundle, so version history inherits the game's encryption state.
   */
  code_bundle: string;
  created_at: Generated<Timestamp>;
  game_id: string;
  id: Generated<string>;
  previous_game_version_id: string | null;
}

export interface InviteCodeRedemptions {
  account_id: string;
  id: Generated<string>;
  invite_code_id: string;
  redeemed_at: Generated<Timestamp>;
}

export interface InviteCodes {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_uses: number | null;
  note: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Kids {
  account_id: string;
  active_persona_id: string | null;
  /**
   * E2EE enc:v1: JSON string { color, avatar } — the kid's chosen look, sealed under the account VMK. Server cannot decrypt.
   */
  avatar_config: string | null;
  /**
   * E2EE enc:v1: JSON array of 3 avatar ids — the optional avatar-PIN puzzle. NULL = disabled. Server cannot decrypt.
   */
  avatar_pin: string | null;
  birthdate: string | null;
  can_add_friends: Generated<boolean>;
  can_be_added_as_friend: Generated<boolean>;
  created_at: Generated<Timestamp>;
  /**
   * Plaintext per-kid date/time display override ({ dateStyle?, timeStyle?, timeZoneEnc? }); absent fields inherit the account default. An explicit timezone is sealed enc:v1: in timeZoneEnc.
   */
  date_preferences: Json | null;
  /**
   * Persisted deaf state: NULL = listens normally; a timestamp = kid turned dodi's listening off (mic muted), so she comes up deaf on connect until re-enabled. Audio OUTPUT, including game-requested speech, stays allowed; full silence is kids.muted_dodi_at. Plaintext operational state.
   */
  deafened_dodi_at: Timestamp | null;
  display_name: string;
  friend_kem_public_key: string | null;
  /**
   * Opaque enc:v1: blob — the kid's ML-KEM/ML-DSA secret keys sealed under the account VMK. Server cannot decrypt.
   */
  friend_secret_keys: string | null;
  friend_sign_public_key: string | null;
  id: Generated<string>;
  incoming_friend_requests_require_parent_approval: Generated<boolean>;
  language: Generated<string>;
  /**
   * E2EE AI briefing dossier markdown; derived from active memories with [source:memory_source_id] citations.
   */
  memory: string | null;
  /**
   * Persisted output mute: NULL = dodi may produce sound; a timestamp = kid muted dodi's audio output (no speech, game-requested speech refused). Orthogonal to deafened_dodi_at (hearing): the two compose freely.
   */
  muted_dodi_at: Timestamp | null;
  outgoing_friend_requests_require_parent_approval: Generated<boolean>;
  parent_notes: string | null;
  social_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Memories {
  account_id: string;
  category: string | null;
  content_enc: string;
  created_at: Generated<Timestamp>;
  discard_memory_source_id: string | null;
  discarded_at: Timestamp | null;
  discarded_by: "system" | "parent" | null;
  id: Generated<string>;
  kid_id: string;
  status: Generated<"active" | "discarded">;
}

export interface MemorySources {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  memory_id: string;
  relation: "supports" | "contradicts";
  transcript_entry_id: string;
}

export interface NewsletterSignups {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  ip_hash: string | null;
  list: Generated<string>;
  locale: Generated<"en" | "de">;
  status: Generated<"confirmed" | "unsubscribed">;
  updated_at: Generated<Timestamp>;
}

export interface Personas {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_system_default: Generated<boolean>;
  name: string;
  soul: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PlatformConfig {
  created_at: Generated<Timestamp>;
  key: string;
  updated_at: Generated<Timestamp>;
  value: Generated<Json>;
}

export interface PlatformPlans {
  created_at: Generated<Timestamp>;
  handle: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_custom_personas: number;
  /**
   * Max kid profiles the plan grants. NULL = unlimited (current value for every plan). Copied onto accounts by applyPlanToAccount.
   */
  max_kids: number | null;
  max_storage_mb_per_kid: number;
  memory_tier: "basic" | "advanced" | "full";
  price_eur_month: Generated<Numeric>;
  sort_order: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface PlatformPlanTranslations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  locale: string;
  plan_id: string;
  tagline: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface TranscriptEntries {
  account_id: string;
  content_enc: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kid_id: string;
  occurred_at: Timestamp;
  role: "dodi" | "kid";
  transcript_id: string;
}

export interface Transcripts {
  account_id: string;
  /**
   * E2EE JSON mirror of all day entries (ids + text); one-decrypt read path for memory processing.
   */
  content_enc: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kid_id: string;
  local_date: string;
  persona_id: string | null;
  processed_at: Timestamp | null;
  status: Generated<"open" | "processed">;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  accounts: Accounts;
  activities: Activities;
  ai_usage_logs: AiUsageLogs;
  auth_accounts: AuthAccounts;
  auth_sessions: AuthSessions;
  auth_users: AuthUsers;
  auth_verifications: AuthVerifications;
  devices: Devices;
  error_logs: ErrorLogs;
  friendships: Friendships;
  game_favorites: GameFavorites;
  game_plays: GamePlays;
  game_publication_requests: GamePublicationRequests;
  game_sharings: GameSharings;
  game_snapshots: GameSnapshots;
  game_translations: GameTranslations;
  game_versions: GameVersions;
  games: Games;
  invite_code_redemptions: InviteCodeRedemptions;
  invite_codes: InviteCodes;
  kids: Kids;
  memories: Memories;
  memory_sources: MemorySources;
  newsletter_signups: NewsletterSignups;
  personas: Personas;
  platform_config: PlatformConfig;
  platform_plan_translations: PlatformPlanTranslations;
  platform_plans: PlatformPlans;
  transcript_entries: TranscriptEntries;
  transcripts: Transcripts;
}
